### ISSUE TITLE
Dependency Issue for adafruit_pycamera?  Missing 'adafruit_lis3dh'

### ISSUE THREAD

**Issue by OpticsBiker** [adafruit/Adafruit_CircuitPython_PyCamera#10]
I ran a circup install with the following screen output
----------
```
(base) PS C:\Users\debl2> circup install adafruit_pycamera
Found device at H:\, running CircuitPython 9.0.0-alpha.6.
Searching for dependencies for: ['adafruit_pycamera']
WARNING:
        typing-extensions is not a known CircuitPython library.
Ready to install: ['adafruit_aw9523', 'adafruit_bus_device', 'adafruit_pycamera', 'adafruit_register']

Installed 'adafruit_aw9523'.
Installed 'adafruit_bus_device'.
Installed 'adafruit_pycamera'.
Installed 'adafruit_register'.
(base) PS C:\Users\debl2>
```
-----------

When I do an 'import adafruit_pycamera' from either the command line in mu Editor or from code containing the import I get the error output below:
--------
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "camTest.py", line 12, in <module>
  File "adafruit_pycamera/__init__.py", line 16, in <module>
ImportError: no module named 'adafruit_lis3dh
```

**Comment by dhalbert** [comment]
This has been fixed by #8 but is not yet in a release.

**Comment by OpticsBiker** [comment]
Do I manually install?

David Lees
From Pixel 6 Pro

**Comment by caternuson** [comment]
Manually installing is always an option:
https://learn.adafruit.com/welcome-to-circuitpython/circuitpython-libraries

circup is just a convenience tool to automate the process

**Comment by dhalbert** [comment]
> Do I manually install?

@OpticsBiker You can install the latest release: https://github.com/adafruit/Adafruit_CircuitPython_PyCamera/releases/tag/0.0.5 manually. It will appear in the bundle overnight.
