### ISSUE TITLE
Fancy camera image file timestamps are all 1999-12-31

### ISSUE THREAD

**Issue by 9037568** [adafruit/Adafruit_CircuitPython_PyCamera#39]
When taking pictures using the Fancy Camera code from [this guide](https://learn.adafruit.com/memento-camera-quick-start-guide/fancy-camera), all the pictures taken are timestamped 1999-12-31.

**Comment by FoamyGuy** [comment]
The help-with-circuitpython channel on the [Adafruit Discord](https://adafru.it/discord) or the [Adafruit forums](https://forums.adafruit.com/viewforum.php?f=60) are the best places to get help with support for projects. 

I think the date being wrong is most likely an indicator that the WIFI setup or NTP time sync did not succeed which then causes the timestamp to revert back to the only known system time which I do believe is around the date you saw.

It looks like the example in that learn guide has some error message like:

Wifi failed to connect. Time not set.

Wifi config not found in settintgs.toml. Time not set.

Those would both indicate an issue with getting the time and afterward the timestamps on the files will not be accurate.

When the time is sync'd successfully it has this printout: `ntp time: {ntp.datetime}` which will show the time that it believes it is. As long as that gets printed and looks accurate then the timestamps on the photos should be as well.
