### ISSUE TITLE
horizontally flipped preview/image 

### ISSUE THREAD

**Issue by jedgarpark** [adafruit/Adafruit_CircuitPython_PyCamera#7]
I'm seeing horizontally flipped/mirrored images in live preview and in saved images when using the examples/camera/code.py
I tried setting `pycam.hmirror = False` but this didn't seem to make a difference.

**Comment by jedgarpark** [comment]
i was able to set the hmirror to False in the library itself to get a non-mirrored live view and stored photo by changing it to `self.camera.hmirror = False` so maybe this could be a choice in the constructor when we create the pycam object in code?

**Comment by caternuson** [comment]
I ran into same thing running the `camera` example.

It's possible to fix in user code with:
```python
pycam.camera.hmirror = False
```

`hmirror` is a property of the `camera` object within the `pycam` instance, not `pycam` itself. 

I just added it after the constructor like this: 
```python
pycam = adafruit_pycamera.PyCamera()
pycam.camera.hmirror = False
```

**Comment by dhalbert** [comment]
Maybe `pycam.camera.hmirror = False` should be the default?

**Comment by caternuson** [comment]
Yep. Agree. But don't know reasoning behind current default in library.
